---
apiVersion: v1
kind: Service
metadata:
  name: demoapp-vote-front
  namespace: {{ NAMESPACE }}
spec:
#  type: LoadBalancer  - Change this as per requirement
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
  selector:
    app: demoapp-vote-front
